<header class="py-3 mb-4 border-bottom">
  <div class="container d-flex flex-wrap justify-content-center">
    <span class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
      <a href="/"><img src="https://brainbox.com.pl/wp-content/uploads/2020/03/logo-brainbox-ciemne.png" class="img-fluid me-3" style="max-width: 180px;" /></a>
      <span class="fs-6">Szybkie indexowanie | Twróca <a href="http://kemuri.codes/">@Marcin Dymek</a></span> <span  <
    </span>
  </div>
</header>
